### ISSUE TITLE
Fix bug with harvesting resources

### ISSUE THREAD

**Issue by MartBakler** [JackHopkins/PaperclipMaximiser#6]
Input
nearest_coal = nearest(Resource.Coal)
move_to(nearest_coal)
harvest_resource(nearest_coal, quantity=10)

Output
'2: ({\'y\': -11.5, \'x\': -10.5}, -1726833231.6635475)\n10: ({\'y\': -11.5, \'x\': 19.5}, -1726833231.6630173)\n11: Error at lines 18-18: (\'Could not harvest.\', \'"global.actions.harvest_resource2 = function(p..."]:167: Could only harvest 9 at position (19.5, -11.5)\')'

**Comment by JackHopkins** [comment]
Cannot replicate. Can you try this on the headless branch please?
